#+TITLE: Sagekit
#+AUTHOR: Jose Perez
#+EMAIL: jose.perez@vertilux.com
#+EXPORT_FILE_NAME: ./docs/index.html
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./docs/css/style.css">
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil

Sagekit is a ruby gem client library to talk with Sage300 API.

The Sage 300 Web API makes it easier to create services that integrate with Sage 300 data and business logic. The Web API improves on existing tools for third-party integrations without requiring in-depth understanding of the Sage 300 View protocol and components.

* Installation

Add this line to your application's Gemfile:

#+begin_src ruby
gem 'sagekit'
#+end_src

And then execute:

#+begin_src bash
$ bundle install
#+end_src

Or install it yourself as:

#+begin_src bash
$ gem install sagekit
#+end_src

* Usage

Make sure you have Sage300 web services up and runing. Web service is an easy way to communicate with 3rd party application without hampering the existing system & this is the reason we will always suggest to go for web service integration, whenever any customer requires integration.

Initialize client to make requets:

#+begin_src ruby
require 'sagekit'
client = Sagekit::Client.new(URL, AUTH)
client.sales_orders.list(COMPANY, '$top':10)
#+end_src

Make sure to change:
- URL with the web serive url, ex: [[http://10.255.6.60/Sage300WebApi/v1.0/-/]]
- AUTH with the Basic authentication key
- COMPANY with teh company id

* Resources

The gem maps as closely as possible to the Sage300 API so you can easily convert API examples to gem code.   
Responses are created as objects like. They're built using OpenStruct so you can easily access data in a Ruby-ish way.

** AR

*** Customers

#+begin_src ruby
client.customers.list('COMPANY')
client.customers.retreive('COMPANY', 'NUMBER')
client.customers.create('COMPANY', {})
client.customers.update('COMPANY', {})
client.customers.delete('COMPANY', 'NUMBER')
#+end_src

*** Customer Groups

#+begin_src ruby
client.customer_groups.list('COMPANY')
client.customer_groups.retreive('COMPANY', 'NUMBER')
client.customer_groups.create('COMPANY', {})
client.customer_groups.update('COMPANY', {})
client.customer_groups.delete('COMPANY', 'NUMBER')
#+end_src

*** Customer Terms

#+begin_src ruby
client.customer_terms.list('COMPANY')
client.customer_terms.retreive('COMPANY', 'NUMBER')
client.customer_terms.create('COMPANY', {})
client.customer_terms.update('COMPANY', {})
client.customer_terms.delete('COMPANY', 'NUMBER')
#+end_src

*** Sales Persons

#+begin_src ruby
client.sales_persons.list('COMPANY')
client.sales_persons.retreive('COMPANY', 'NUMBER')
client.sales_persons.create('COMPANY', {})
client.sales_persons.update('COMPANY', {})
client.sales_persons.delete('COMPANY', 'NUMBER')
client.sales_persons.statistics('COMPANY')
client.sales_persons.filter_stats('COMPANY', 'SALESPERSON', 'YEAR', 'PERIDO')
#+end_src

** AP

*** Vendors

#+begin_src ruby
client.vendors.list('COMPANY')
client.vendors.retreive('COMPANY', 'NUMBER')
client.vendors.create('COMPANY', {})
client.vendors.update('COMPANY', {})
client.vendors.delete('COMPANY', 'NUMBER')
client.vendors.statistics('COMPANY', 'NUMBER')
#+end_src

*** Vendor Groups

#+begin_src ruby
client.vendor_groups.list('COMPANY')
client.vendor_groups.retreive('COMPANY', 'NUMBER')
client.vendor_groups.create('COMPANY', {})
client.vendor_groups.update('COMPANY', {})
client.vendor_groups.delete('COMPANY', 'NUMBER')
#+end_src

*** Vendor Terms

#+begin_src ruby
client.vendor_terms.list('COMPANY')
client.vendor_terms.retreive('COMPANY', 'NUMBER')
client.vendor_terms.create('COMPANY', {})
client.vendor_terms.update('COMPANY', {})
client.vendor_terms.delete('COMPANY', 'NUMBER')
#+end_src

** IC

*** Items

#+begin_src ruby
client.items.list('COMPANY')
client.items.retreive('COMPANY', 'NUMBER')
client.items.create('COMPANY', {})
client.items.update('COMPANY', {})
client.items.delete('COMPANY', 'NUMBER')
#+end_src

*** Categories

#+begin_src ruby
client.categories.list('COMPANY')
client.categories.retreive('COMPANY', 'NUMBER')
client.categories.create('COMPANY', {})
client.categories.update('COMPANY', {})
client.categories.delete('COMPANY', 'NUMBER')
#+end_src

*** Locations

#+begin_src ruby
client.locations.list('COMPANY')
client.locations.retreive('COMPANY', 'LOC_KEY')
client.locations.create('COMPANY', {})
client.locations.update('COMPANY', {})
client.locations.delete('COMPANY', 'NUMBER')
#+end_src

** OE

*** Sales Orders

#+begin_src ruby
client.items.list('COMPANY')
client.items.retreive('COMPANY', 'ID')
client.items.create('COMPANY', {})
#+end_src

*** Invoices

#+begin_src ruby
client.items.list('COMPANY')
client.items.retreive('COMPANY', 'ID')
#+end_src

*** Sales History

#+begin_src ruby
client.sales_history.list('COMPANY', {})
client.sales_history.details('COMPANY', {})
client.sales_history.stats('COMPANY', {})
#+end_src

* Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/lepepe/sagekit. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the [[https://github.com/lepepe/sagekit/blob/master/CODE_OF_CONDUCT.md][code of conduct]]

* License

The gem is available as open source under the terms of the [[https://opensource.org/licenses/MIT][MIT License]].

* Code of Conduct

Everyone interacting in the Sagekit project's codebases, issue trackers, chat rooms and mailing lists is expected to follow the [[https://github.com/lepepe/sagekit/blob/master/CODE_OF_CONDUCT.md][code of conduct]].
